from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import yaml

from ai_scientist.resources import bfts_config_path
from ai_scientist.utils.atomic_io import atomic_write_text
from ai_scientist.utils.privacy import REDACTED_PATH, portable_path
from ._version import __version__
from .dependency_profiles import (
    capability_installation_command,
    capability_installation_spec,
    installation_command,
)
from .provider_config import (
    DEFAULT_MODELS,
    PROVIDER_FIELDS,
    ProviderConfigError,
    provider_config_payload,
    validate_provider_model,
)


class WorkspaceInitError(ValueError):
    """Raised when a workspace cannot be created without surprising data loss."""


PROVIDER_ENV_LINES: dict[str, tuple[str, ...]] = {
    provider: tuple(
        f"{field.name}={field.default or 'replace-me'}"
        for field in fields
        if field.required or field.default is not None or provider == "vertex_ai"
    )
    for provider, fields in PROVIDER_FIELDS.items()
}

WORKSPACE_FILES = (
    ".dockerignore",
    ".env.example",
    ".gitignore",
    ".xscientist/providers.json",
    "Dockerfile.executor",
    "README.md",
    "bfts_config.yaml",
    "topic.md",
)


def _resolve_model(provider: str, model: str | None) -> str:
    try:
        _provider, selected = validate_provider_model(provider, model)
    except ProviderConfigError as exc:
        raise WorkspaceInitError(str(exc)) from exc
    return selected


def _render_bfts_config(profile: str, model: str) -> str:
    with bfts_config_path(profile).open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle)
    if not isinstance(payload, dict):
        raise WorkspaceInitError(f"packaged BFTS profile {profile!r} is invalid")

    image = f"xscientist-exec:{__version__}"
    exec_config = payload.setdefault("exec", {})
    exec_config["backend"] = "docker"
    exec_config["require_isolation"] = True
    exec_config["docker_image"] = image
    budget = payload.setdefault("llm_budget", {})
    budget["max_total_tokens"] = 2_000_000 if profile == "deep" else 500_000
    budget["max_wall_time_seconds"] = 86_400 if profile == "deep" else 21_600
    payload.setdefault("report", {})["model"] = model
    agent = payload.setdefault("agent", {})
    for key in ("code", "feedback", "vlm_feedback"):
        agent.setdefault(key, {})["model"] = model
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    return f"# Generated by xscientist init from the {profile!r} profile.\n{body}"


def _render_env(provider: str) -> str:
    provider_lines = "\n".join(PROVIDER_ENV_LINES[provider])
    return (
        "# Example only. Prefer `xscientist provider add` for hidden API-key input.\n"
        "# A private .env created by that command is loaded inside this workspace.\n"
        "# Never commit .env.\n\n"
        "RESEARCH_OUTPUT_DIR=./outputs\n"
        f"{provider_lines}\n"
    )


def _render_dockerfile(
    provider: str,
    *,
    capabilities: tuple[str, ...] | None = None,
    provider_required: bool = True,
) -> str:
    selected = (
        capabilities if capabilities is not None else ("research", "ml", "pdf-layout")
    )
    runtime_spec = capability_installation_spec(
        selected,
        provider=provider if provider_required else None,
        version="${XSCIENTIST_VERSION}",
    )
    torch_install = (
        "RUN python -m pip install --no-cache-dir \\\n    torch --index-url https://download.pytorch.org/whl/cpu\n"
        if "ml" in selected
        else ""
    )
    return f"""FROM python:3.11-slim

ARG XSCIENTIST_VERSION={__version__}
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1

RUN apt-get update \\
    && apt-get install -y --no-install-recommends build-essential git \\
    && rm -rf /var/lib/apt/lists/*
{torch_install}
RUN python -m pip install --no-cache-dir "{runtime_spec}"

RUN useradd --create-home --uid 10001 scientist
USER scientist
WORKDIR /workspace

CMD ["python", "--version"]
"""


def _render_topic() -> str:
    return """# Research question

State one concrete, falsifiable research question here.

## Hypothesis

Describe the primary hypothesis and the observation that would falsify it.

## Evidence plan

- Baselines and ablations:
- Metrics and uncertainty estimates:
- Fixed datasets or synthetic fixtures:
- Compute, token, and cost budget:
- Stop conditions:

## Constraints

- Preserve failed and negative results.
- Do not make claims without traceable evidence.
- Record seeds, environment details, and evaluation decisions.
"""


def _render_readme(
    *,
    profile: str,
    provider: str,
    model: str,
    task: str = "research",
    capabilities: tuple[str, ...] | None = None,
    provider_required: bool = True,
) -> str:
    image = f"xscientist-exec:{__version__}"
    install = (
        installation_command(provider, version=__version__)
        if capabilities is None
        else capability_installation_command(
            capabilities,
            provider=provider if provider_required else None,
            version=__version__,
        )
    )
    install_note = (
        f"This installs the selected capabilities and only the `{provider}` client."
        if provider_required
        else "This task is provider-neutral, so no model client is installed."
    )
    provider_note = (
        f"""```bash
xscientist provider add {provider}
xscientist provider list
```

The command reuses the model `{model}` selected during setup and prompts for
missing secrets with hidden input. Existing process environment variables take
precedence and are never copied to disk implicitly."""
        if provider_required
        else "This task does not require an LLM provider. Add one later only when a selected task requests it."
    )
    return f"""# XScientist workspace

Generated for XScientist {__version__} with provider `{provider}`, model
`{model}`, and the packaged BFTS `{profile}` configuration.

No API key was generated by `xscientist init`. Credentials added below are
written to a Git-ignored `.env` with user-only permissions; command output and
provider metadata never contain the secret value.

## 1. Install

```bash
{install}
```

{install_note}
Specialist stacks remain opt-in: add `ml`, `pdf-layout`, or `service` to the
bracketed extras when the study actually needs them. The legacy `full` extra
remains available for an all-provider environment.

## 2. Run the unified doctor

```bash
xscientist doctor --task {task}
```

This verifies task modules, the provider, login, and the local persistence
backend with the branch/safe-merge capabilities used by Research VCS. It does
not contact a remote. Use `xscientist git doctor` for the backend-only view.

## 3. Add the provider when required

{provider_note}

## 4. Create a local login

```bash
xscientist auth login --user <your-name>
```

## 5. Build the isolated experiment image

```bash
docker build -f Dockerfile.executor -t {image} .
```

The generated BFTS config fails closed if this image is unavailable. It does
not silently execute AI-generated experiment code in the host Python process.

## 6. Check the exact runtime configuration

```bash
xscientist doctor --task {task} --deep
```

This checks the selected model credentials and client package as well as the
Docker daemon and exact image tag before any paid model call starts. The legacy
low-level equivalent remains `xscientist preflight --strict --bfts-config
bfts_config.yaml`.

## 7. Run one traceable study

Edit `topic.md`, then run:

```bash
xscientist project first-study \\
  --output-root ./outputs \\
  --topic topic.md \\
  --bfts-config bfts_config.yaml \\
  --num-ideas 1
```

Inspect the outputs without starting another model call:

```bash
xscientist manager --research-dir ./outputs list-papers
xscientist research status --repo outputs/projects/first-study
xscientist research objects --repo outputs/projects/first-study
xscientist research audit --repo outputs/projects/first-study --level trace
```

Use `xscientist project --help` for all quality, budget, workflow, and venue
options. The generated config has finite token and wall-time limits. API calls
can still incur cost; add a provider-specific `max_cost_usd` and pricing under
`llm_budget` before a real run.
"""


def _render_files(
    *,
    profile: str,
    provider: str,
    model: str,
    task: str = "research",
    capabilities: tuple[str, ...] | None = None,
    provider_required: bool = True,
) -> dict[str, str]:
    secret_ignores = (
        ".env\n"
        ".env.*\n"
        "!.env.example\n"
        ".secrets/\n"
        "*.pem\n"
        "*.key\n"
        "credentials.json\n"
        "secrets.json\n"
    )
    return {
        ".dockerignore": secret_ignores + "outputs/\n__pycache__/\n*.py[cod]\n",
        ".env.example": _render_env(provider),
        ".gitignore": secret_ignores + "outputs/\n__pycache__/\n*.py[cod]\n",
        ".xscientist/providers.json": json.dumps(
            provider_config_payload(provider=provider, model=model),
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        "Dockerfile.executor": _render_dockerfile(
            provider,
            capabilities=capabilities,
            provider_required=provider_required,
        ),
        "README.md": _render_readme(
            profile=profile,
            provider=provider,
            model=model,
            task=task,
            capabilities=capabilities,
            provider_required=provider_required,
        ),
        "bfts_config.yaml": _render_bfts_config(profile, model),
        "topic.md": _render_topic(),
    }


def create_workspace(
    directory: str | Path,
    *,
    profile: str = "default",
    provider: str = "zhipu",
    model: str | None = None,
    force: bool = False,
    task: str = "research",
    capabilities: Iterable[str] | None = None,
    provider_required: bool = True,
) -> dict[str, Any]:
    """Create a safe, installed-package-first XScientist workspace."""
    normalized_profile = str(profile or "default").strip().lower()
    normalized_provider = str(provider or "zhipu").strip().lower()
    if normalized_provider not in PROVIDER_ENV_LINES:
        choices = ", ".join(sorted(PROVIDER_ENV_LINES))
        raise WorkspaceInitError(
            f"unknown provider {provider!r}; expected one of: {choices}"
        )
    selected_model = _resolve_model(normalized_provider, model)
    selected_capabilities = (
        tuple(dict.fromkeys(str(item) for item in capabilities))
        if capabilities is not None
        else None
    )
    files = _render_files(
        profile=normalized_profile,
        provider=normalized_provider,
        model=selected_model,
        task=str(task or "research"),
        capabilities=selected_capabilities,
        provider_required=provider_required,
    )

    root = Path(directory).expanduser().resolve()
    if root.exists() and not root.is_dir():
        raise WorkspaceInitError("workspace path is not a directory")
    conflicts = [name for name in WORKSPACE_FILES if (root / name).exists()]
    directory_conflicts = [name for name in conflicts if (root / name).is_dir()]
    if directory_conflicts:
        raise WorkspaceInitError(
            "workspace contains directories where files are required: "
            + ", ".join(directory_conflicts)
        )
    if conflicts and not force:
        raise WorkspaceInitError(
            "refusing to overwrite existing workspace files: "
            + ", ".join(conflicts)
            + "; pass --force to replace only these generated files"
        )

    root.mkdir(parents=True, exist_ok=True)
    for relative, content in files.items():
        atomic_write_text(root / relative, content)

    workspace_view = portable_path(root, base=Path.cwd())
    if workspace_view == REDACTED_PATH:
        workspace_view = "<workspace>"
    return {
        "ok": True,
        "workspace": workspace_view,
        "profile": normalized_profile,
        "provider": normalized_provider,
        "model": selected_model,
        "files": list(WORKSPACE_FILES),
        "secrets_written": False,
        "next_steps": [
            f"cd {workspace_view}",
            (
                installation_command(normalized_provider, version=__version__)
                if selected_capabilities is None
                else capability_installation_command(
                    selected_capabilities,
                    provider=(normalized_provider if provider_required else None),
                    version=__version__,
                )
            ),
            "xscientist git doctor",
            f"xscientist provider add {normalized_provider}",
            "xscientist auth login --user <your-name>",
            f"docker build -f Dockerfile.executor -t xscientist-exec:{__version__} .",
            "xscientist preflight --strict --bfts-config bfts_config.yaml",
            "edit topic.md, then follow README.md",
        ],
    }


__all__ = [
    "DEFAULT_MODELS",
    "PROVIDER_ENV_LINES",
    "WORKSPACE_FILES",
    "WorkspaceInitError",
    "create_workspace",
]
