from __future__ import annotations

import shlex
from pathlib import Path
from typing import Any

import yaml

from ai_scientist.resources import bfts_config_path
from ai_scientist.utils.atomic_io import atomic_write_text
from ai_scientist.utils.provider_registry import resolve_model_provider

from ._version import __version__


class WorkspaceInitError(ValueError):
    """Raised when a workspace cannot be created without surprising data loss."""


PROVIDER_ENV_LINES: dict[str, tuple[str, ...]] = {
    "zhipu": ("ZHIPU_API_KEY=replace-me",),
    "openai": ("OPENAI_API_KEY=replace-me",),
    "anthropic": ("ANTHROPIC_API_KEY=replace-me",),
    "deepseek": ("DEEPSEEK_API_KEY=replace-me",),
    "gemini": ("GEMINI_API_KEY=replace-me",),
    "openrouter": ("OPENROUTER_API_KEY=replace-me",),
    "huggingface": ("HUGGINGFACE_API_KEY=replace-me",),
    "ollama": ("OLLAMA_BASE_URL=http://localhost:11434/v1",),
    "openai_compat": (
        "OPENAI_COMPAT_API_KEY=replace-me",
        "OPENAI_COMPAT_BASE_URL=https://example.invalid/v1",
    ),
    "bedrock": (
        "AWS_ACCESS_KEY_ID=replace-me",
        "AWS_SECRET_ACCESS_KEY=replace-me",
        "AWS_REGION_NAME=replace-me",
    ),
    "vertex_ai": (
        "GOOGLE_CLOUD_PROJECT=replace-me",
        "CLOUD_ML_REGION=replace-me",
    ),
}

DEFAULT_MODELS = {
    "zhipu": "glm-4-flash",
}

WORKSPACE_FILES = (
    ".env.example",
    ".gitignore",
    "Dockerfile.executor",
    "README.md",
    "bfts_config.yaml",
    "topic.md",
)


def _resolve_model(provider: str, model: str | None) -> str:
    selected = str(model or DEFAULT_MODELS.get(provider) or "").strip()
    if not selected:
        raise WorkspaceInitError(
            f"--model is required for provider {provider!r}; use a current model ID "
            f"with the provider prefix, for example {provider}/<model>."
        )
    spec = resolve_model_provider(selected)
    if spec.provider != provider:
        raise WorkspaceInitError(
            f"model {selected!r} resolves to provider {spec.provider!r}, not "
            f"the selected provider {provider!r}"
        )
    return selected


def _render_bfts_config(profile: str, model: str) -> str:
    with bfts_config_path(profile).open("r", encoding="utf-8") as handle:
        payload = yaml.safe_load(handle)
    if not isinstance(payload, dict):
        raise WorkspaceInitError(f"packaged BFTS profile {profile!r} is invalid")

    image = f"xscientist-exec:{__version__}"
    exec_config = payload.setdefault("exec", {})
    exec_config["backend"] = "docker"
    exec_config["require_isolation"] = True
    exec_config["docker_image"] = image
    payload.setdefault("report", {})["model"] = model
    agent = payload.setdefault("agent", {})
    for key in ("code", "feedback", "vlm_feedback"):
        agent.setdefault(key, {})["model"] = model
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    return f"# Generated by xscientist init from the {profile!r} profile.\n{body}"


def _render_env(provider: str) -> str:
    provider_lines = "\n".join(PROVIDER_ENV_LINES[provider])
    return (
        "# XScientist does not load this file automatically.\n"
        "# Copy it to .env, replace placeholders, then export it in your shell.\n"
        "# Never commit .env.\n\n"
        "RESEARCH_OUTPUT_DIR=./outputs\n"
        f"{provider_lines}\n"
    )


def _render_dockerfile() -> str:
    return f"""FROM python:3.11-slim

ARG XSCIENTIST_VERSION={__version__}
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PYTHONUNBUFFERED=1

RUN apt-get update \\
    && apt-get install -y --no-install-recommends build-essential git \\
    && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --no-cache-dir \\
    torch --index-url https://download.pytorch.org/whl/cpu
RUN python -m pip install --no-cache-dir "xscientist[full]==${{XSCIENTIST_VERSION}}"

RUN useradd --create-home --uid 10001 scientist
USER scientist
WORKDIR /workspace

CMD ["python", "--version"]
"""


def _render_topic() -> str:
    return """# Research question

State one concrete, falsifiable research question here.

## Hypothesis

Describe the primary hypothesis and the observation that would falsify it.

## Evidence plan

- Baselines and ablations:
- Metrics and uncertainty estimates:
- Fixed datasets or synthetic fixtures:
- Compute, token, and cost budget:
- Stop conditions:

## Constraints

- Preserve failed and negative results.
- Do not make claims without traceable evidence.
- Record seeds, environment details, and evaluation decisions.
"""


def _shell_model_args(model: str) -> str:
    quoted = shlex.quote(model)
    options = (
        "model-ideation",
        "model-agg-plots",
        "model-writeup",
        "model-writeup-small",
        "model-citation",
        "model-review",
    )
    continuation = "\\"
    separator = f" {continuation}\n  "
    return separator.join(f"--{option} {quoted}" for option in options)


def _render_readme(*, profile: str, provider: str, model: str) -> str:
    powershell_env = "\n".join(
        f'$env:{name} = "{value}"'
        for name, value in (line.split("=", 1) for line in PROVIDER_ENV_LINES[provider])
    )
    model_args = _shell_model_args(model)
    image = f"xscientist-exec:{__version__}"
    return f"""# XScientist workspace

Generated for XScientist {__version__} with provider `{provider}`, model
`{model}`, and the packaged BFTS `{profile}` configuration.

No API key is stored in this workspace. `.env` is ignored by Git and must stay
local.

## 1. Install

```bash
python -m pip install "xscientist[full]=={__version__}"
```

## 2. Configure credentials and output

POSIX shells:

```bash
cp .env.example .env
# Edit .env first, then export its values into this shell.
set -a
. ./.env
set +a
```

PowerShell:

```powershell
$env:RESEARCH_OUTPUT_DIR = "$PWD/outputs"
{powershell_env}
```

XScientist deliberately does not auto-load `.env`: secrets are only made
available when you explicitly export them.

## 3. Create a local login

```bash
xscientist auth login --user <your-name>
```

## 4. Build the isolated experiment image

```bash
docker build -f Dockerfile.executor -t {image} .
```

The generated BFTS config fails closed if this image is unavailable. It does
not silently execute AI-generated experiment code in the host Python process.

## 5. Check the exact runtime configuration

```bash
xscientist preflight --strict --bfts-config bfts_config.yaml
```

This checks the selected model credentials and client package as well as the
Docker daemon and exact image tag before any paid model call starts.

## 6. Run one traceable study

Edit `topic.md`, then run:

```bash
xscientist project first-study \\
  --topic topic.md \\
  --bfts-config bfts_config.yaml \\
  --num-ideas 1 \\
  {model_args} \\
  --research-git local
```

Inspect the outputs without starting another model call:

```bash
xscientist manager list
xscientist research status --repo outputs/projects/first-study
```

Use `xscientist project --help` for all quality, budget, workflow, and venue
options. API calls can incur cost; set explicit limits under `llm_budget` in
`bfts_config.yaml` before a real run.
"""


def _render_files(*, profile: str, provider: str, model: str) -> dict[str, str]:
    return {
        ".env.example": _render_env(provider),
        ".gitignore": ".env\noutputs/\n__pycache__/\n*.py[cod]\n",
        "Dockerfile.executor": _render_dockerfile(),
        "README.md": _render_readme(
            profile=profile,
            provider=provider,
            model=model,
        ),
        "bfts_config.yaml": _render_bfts_config(profile, model),
        "topic.md": _render_topic(),
    }


def create_workspace(
    directory: str | Path,
    *,
    profile: str = "default",
    provider: str = "zhipu",
    model: str | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """Create a safe, installed-package-first XScientist workspace."""
    normalized_profile = str(profile or "default").strip().lower()
    normalized_provider = str(provider or "zhipu").strip().lower()
    if normalized_provider not in PROVIDER_ENV_LINES:
        choices = ", ".join(sorted(PROVIDER_ENV_LINES))
        raise WorkspaceInitError(
            f"unknown provider {provider!r}; expected one of: {choices}"
        )
    selected_model = _resolve_model(normalized_provider, model)
    files = _render_files(
        profile=normalized_profile,
        provider=normalized_provider,
        model=selected_model,
    )

    root = Path(directory).expanduser().resolve()
    if root.exists() and not root.is_dir():
        raise WorkspaceInitError(f"workspace path is not a directory: {root}")
    conflicts = [name for name in WORKSPACE_FILES if (root / name).exists()]
    directory_conflicts = [name for name in conflicts if (root / name).is_dir()]
    if directory_conflicts:
        raise WorkspaceInitError(
            "workspace contains directories where files are required: "
            + ", ".join(directory_conflicts)
        )
    if conflicts and not force:
        raise WorkspaceInitError(
            "refusing to overwrite existing workspace files: "
            + ", ".join(conflicts)
            + "; pass --force to replace only these generated files"
        )

    root.mkdir(parents=True, exist_ok=True)
    for relative, content in files.items():
        atomic_write_text(root / relative, content)

    return {
        "ok": True,
        "workspace": str(root),
        "profile": normalized_profile,
        "provider": normalized_provider,
        "model": selected_model,
        "files": list(WORKSPACE_FILES),
        "secrets_written": False,
        "next_steps": [
            f"cd {shlex.quote(str(root))}",
            "copy .env.example to .env, replace placeholders, and export it",
            "xscientist auth login --user <your-name>",
            f"docker build -f Dockerfile.executor -t xscientist-exec:{__version__} .",
            "xscientist preflight --strict --bfts-config bfts_config.yaml",
            "edit topic.md, then follow README.md",
        ],
    }


__all__ = [
    "DEFAULT_MODELS",
    "PROVIDER_ENV_LINES",
    "WORKSPACE_FILES",
    "WorkspaceInitError",
    "create_workspace",
]
